//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPAPP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblBOM> tblBOM { get; set; }
        public virtual DbSet<tblBrand> tblBrand { get; set; }
        public virtual DbSet<tblDCate> tblDCate { get; set; }
        public virtual DbSet<tblFactory> tblFactory { get; set; }
        public virtual DbSet<tblICate> tblICate { get; set; }
        public virtual DbSet<tblItem> tblItem { get; set; }
        public virtual DbSet<tblLine> tblLine { get; set; }
        public virtual DbSet<tblMachine> tblMachine { get; set; }
        public virtual DbSet<tblMaterial> tblMaterial { get; set; }
        public virtual DbSet<tblMcCate> tblMcCate { get; set; }
        public virtual DbSet<tblMES> tblMES { get; set; }
        public virtual DbSet<tblMRP> tblMRP { get; set; }
        public virtual DbSet<tblOperation> tblOperation { get; set; }
        public virtual DbSet<tblOrder> tblOrder { get; set; }
        public virtual DbSet<tblPart> tblPart { get; set; }
        public virtual DbSet<tblProduction> tblProduction { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblWorker> tblWorker { get; set; }
    }
}
