//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPAPP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMRP
    {
        public int MRPId { get; set; }
        public string MRPCode { get; set; }
        public string ProductionCode { get; set; }
        public string ItemCode { get; set; }
        public string MaterialCode { get; set; }
        public string SupplyCode { get; set; }
        public System.DateTime ShipDate { get; set; }
        public int Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string RegID { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public string ModID { get; set; }
    
        public virtual tblProduction tblProduction { get; set; }
    }
}
