//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPAPP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMES
    {
        public int MESIdx { get; set; }
        public string ProductionCode { get; set; }
        public string ITEMCode { get; set; }
        public int OpIdx { get; set; }
        public string MachineCode { get; set; }
        public string IoTConnect { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<double> PrepareTime { get; set; }
        public Nullable<double> WorkTime { get; set; }
        public Nullable<double> TotalTime { get; set; }
        public Nullable<bool> Defect { get; set; }
    
        public virtual tblProduction tblProduction { get; set; }
    }
}
