//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPAPP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOperation
    {
        public int OpId { get; set; }
        public string OpName { get; set; }
        public Nullable<int> PreOp { get; set; }
        public Nullable<int> PostOp { get; set; }
        public int CycleTime { get; set; }
        public string ItemCode { get; set; }
        public string McateCode { get; set; }
    
        public virtual tblItem tblItem { get; set; }
    }
}
