//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPAPP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPart()
        {
            this.tblBOM = new HashSet<tblBOM>();
        }
    
        public int PartId { get; set; }
        public string PartCode { get; set; }
        public string PartName { get; set; }
        public int PartLevel { get; set; }
        public string UpPart { get; set; }
        public string ItemCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBOM> tblBOM { get; set; }
        public virtual tblItem tblItem { get; set; }
    }
}
